### ISSUE TITLE
Error! While installing npm

### ISSUE THREAD

**Issue by Achaleshwar-singh** [insidesherpa/JPMC-tech-task-2#66]
i am getting an error while installing npm, Please refer to below screenshots.
![errorpage1](https://user-images.githubusercontent.com/29178380/81000547-0d588400-8e64-11ea-96c7-1d3ac88086c5.JPG)
![errorpage2](https://user-images.githubusercontent.com/29178380/81000553-0f224780-8e64-11ea-8a0f-900cd8f54c5a.JPG)
![errorpage3](https://user-images.githubusercontent.com/29178380/81000555-0fbade00-8e64-11ea-9917-9215e1ecff0e.JPG)

**Comment by SHREYASH-MUKESH** [comment]
try using this it worked for me
_Originally posted by @SHREYASH-MUKESH in https://github.com/insidesherpa/JPMC-tech-task-2/issues/72#issuecomment-625046972_

**Comment by rdagrawal** [comment]
![Capture2](https://user-images.githubusercontent.com/54057778/81476236-6b9fb100-922e-11ea-81b2-3f10c26b7366.JPG)
I am also facing the same issue but uninstalling and reinstalling is not a good practice. I think we have to find the solution and reason behind the error. We have to be aware of the issues so that if we face same issue in future then we have a solution for it.

**Comment by rdagrawal** [comment]
try `npm install --ignore-scripts` then run npm start it will work properly

**Comment by Achaleshwar-singh** [comment]
Yes, we have simple solution for this problem visit page no 65 in given pdf from there you can download node_modules. Just replace that node_modules with the actual node_modules which are in your JPMC-tech-task-2 folder. After doing this you can simple start npm, no need to install npm and other dependencies.
try this if you still have any issue please let me know.

**Comment by rdagrawal** [comment]
my issue is solved with `npm install --ignore-scripts`.

thanks.
please close the issue if done.

**Comment by Sankalparora** [comment]
@Achaleshwar-singh im still getting an error after replacing the node modules

**Comment by Achaleshwar-singh** [comment]
@Sankalparora 
What's the error you are getting.
